CREATE TABLE EMPLOYEE (
    ID UUID PRIMARY KEY NOT NULL,
    DOCUMENT VARCHAR(11) NOT NULL,
    USERNAME VARCHAR NOT NULL,
    PASSWORD VARCHAR NOT NULL,
    TOKEN VARCHAR NOT NULL
);

CREATE TABLE CUSTOMER (
    ID UUID PRIMARY KEY NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DOCUMENT VARCHAR(11) NOT NULL,
    PHONE VARCHAR NOT NULL,
    BIRTH DATE NOT NULL
);

CREATE TABLE CAR (
    ID UUID PRIMARY KEY NOT NULL,
    BOARD VARCHAR NOT NULL,
    MODEL VARCHAR NOT NULL,
    COLOR VARCHAR NOT NULL
);

CREATE TABLE CHECKIN (
    ID UUID PRIMARY KEY NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    GARAGE BOOLEAN NOT NULL,
    TOTAL NUMERIC NOT NULL
);

CREATE TABLE ROOM (
    ID UUID PRIMARY KEY NOT NULL,
    NUMBER INT NOT NULL,
    STATUS VARCHAR NOT NULL
);